"""
REQUIREMENTS
- running the script on a control PC/HIVE connected to the IM
- have the IM software opened in parallel of Fiji
- the option "Block remote connection" of the IM software disabled in the admin panel (contact your system administrator or the acquifer support)

This script demonstrates how to start an acquisition from an external application, using a pre-existing imaging machine script file (.imsf), as generated by the IM software.
The script will first open the lid, wait for 3 seconds, close the lid and run the script.
This script could be adapted for robotic workflow for instance, where instead of wait, a robotic arm could install a new plate.

The experiment file (.imsf) contains all the information to run the experiment (well coordinates, channels, camera settings, image directory)
therefore no other command is usually needed in this scenario. 

See the API documentation for the list of commands available by TcpIp and their docstrings. 
https://acquifer.github.io/acquifer-core/acquifer/core/TcpIp.html
"""
from acquifer.core import TcpIp
from java.lang import Thread

try : 
	myIM = TcpIp() # open the communication port with the IM

except Error, error :
	IJ.error(error.getMessage())
	raise Exception(error) # still throw an error to interrupt code execution

myIM.openLid() 

# Or commands for a robotic arm to put a new plate
Thread.sleep(3000) # pause execution for 3 seconds

myIM.closeLid()

# Here we use a raw-string (prefixed with r), to prevent backslash to be interpreted as special character such as new line for \n
# You dont need raw string if your path is using forward slash / or double back slash \\ as separator
experimentPath = r"C:\Users\Admin\Example\myScript.imsf"
myIM.runScript(experimentPath) # This will pause further code execution until the script is finished running

# Just close the port once the script is finished, also switching off any light source if any
myIM.closeConnection()
print "Done"
# You could even put some custom code here to send a mail notification once the experiment is over